on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  validate:
    name: Validate HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test with Nu Validator
        uses: Cyb3r-Jak3/html5validator-action@2a593a9f2c10593cbac84791a6fc4c47e9a106c8
        with:
          root: "."
